PositiveDairyProject/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('', include('dairyApp.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT, })]

accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

dairyApp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('post_dairy_content', views.post_dairy_content, name='post_dairy_content'),
    path('get_dairy_content/', views.get_dairy_content, name='get_dairy_content'),
    path('delete_dairy_content/', views.delete_dairy_content, name='delete_dairy_content'),
    path('create_category/', views.CreateCategoryView.as_view(), name='create_category'),
    path('edit_category/<int:pk>', views.EditCategoryView.as_view(), name='edit_category'),
    path('delete_category/<int:pk>', views.DeleteCategoryView.as_view(), name='delete_category'),
    path('show_pictures/', views.ShowPicturesView.as_view(), name='show_pictures'),
    path('show_pictures/<int:category_id>', views.ShowPicturesView.as_view(), name='show_pictures'),
    path('create_dairy_picture/<str:date>', views.create_dairy_picture, name='create_dairy_picture'),
    path('delete_dairy_picture/<int:pk>', views.DeleteDairyPictureView.as_view(), name='delete_dairy_picture'),
    path('edit_dairy_picture/<int:pk>', views.EditDairyPictureView.as_view(), name='edit_dairy_picture'),
    path('get_dairy_picture/', views.get_dairy_picture, name='get_dairy_picture'),
]

dairyApp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from cloudinary.models import CloudinaryField


class DairyContent(models.Model):
    content = models.TextField(
        max_length=300, verbose_name='楽しかったことを記入しよう', null=True, blank=True)
    date = models.DateField(null=False, blank=True)
    ranking = models.IntegerField(null=False, blank=True)
    user_object = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="dairyContent")

    def __str__(self):
        return self.content


class PictureCategory(models.Model):
    title = models.CharField(max_length=60, verbose_name='カテゴリーのタイトル')
    comment = models.TextField(null=True, blank=True, max_length='200')
    picture_count = models.IntegerField(default=0)
    user_object = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="pictureCategory", blank=True, null=False)

    def __str__(self):
        return self.title


class DairyPicture(models.Model):
    title = models.CharField(max_length=60, verbose_name='写真のタイトル')
    date = models.DateField(null=False, blank=True)
    # image = models.ImageField(upload_to='images')
    image = CloudinaryField(
        'image', folder="images/cloudinary")
    comment = models.TextField(max_length=200, null=True, blank=True)
    category = models.ForeignKey(PictureCategory, on_delete=models.SET_NULL, related_name="dairyPicture", null=True,
                                 default=None)
    user_object = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="dairyPicture")

    def __str__(self):
        return self.title

dairyApp/forms.py
from django import forms
from .models import PictureCategory, DairyPicture


class CategoryForm(forms.ModelForm):
    class Meta:
        model = PictureCategory
        fields = ['title', 'comment']

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs['class'] = 'border-2 border-black py-5 align-middle'
        self.fields['title'].widget.attrs['rows'] = 1
        self.fields['comment'].widget.attrs['class'] = 'border-2 border-black py-5 align-middle'


class DairyPictureForm(forms.ModelForm):
    class Meta:
        model = DairyPicture
        fields = ['title', 'comment', 'image', 'category']

    def __init__(self, user_object, *args, **kwargs):
        self.user_object = user_object
        super(DairyPictureForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = PictureCategory.objects.filter(user_object=self.user_object)
        self.fields['category'].required = False
        self.fields['category'].widget.attrs['class'] = 'border-2 border-black py-3 align-middle'
        self.fields['title'].widget.attrs['class'] = 'border-2 border-black py-3 align-middle'
        self.fields['comment'].widget.attrs['class'] = 'border-2 border-black py-3 align-middle'

dairyApp/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, JsonResponse, Http404, HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST, require_GET
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from .models import DairyContent, PictureCategory, DairyPicture
from .forms import CategoryForm, DairyPictureForm
import datetime
import json


def create_date_obj(date: str) -> datetime:
    return datetime.datetime.strptime(date, '%Y-%m-%d').date()


@login_required
def index(request: HttpRequest):
    print(request.user.email)
    context = {
        'today': datetime.date.today().strftime("%Y-%m-%d"),
    }
    print(context)
    return render(request, 'dairyApp/index.html', context)


@login_required
@require_POST
def post_dairy_content(request: HttpRequest) -> JsonResponse:
    dairy_content = {
        'content': request.POST.get('content'),
        'date': request.POST.get('date'),
        'ranking': request.POST.get('ranking'),
    }

    try:
        instance = DairyContent.objects.get(user_object=request.user,
                                            date=create_date_obj(
                                                dairy_content['date']),
                                            ranking=dairy_content['ranking'], )
        instance.content = dairy_content['content']
        instance.save()
    except DairyContent.DoesNotExist:
        DairyContent.objects.create(user_object=request.user, date=create_date_obj(dairy_content['date']),
                                    ranking=dairy_content['ranking'], content=dairy_content['content'])
    return JsonResponse({
        'dairyContent': dairy_content
    })


@login_required
@require_GET
def get_dairy_content(request: HttpRequest) -> JsonResponse:
    ranking = request.GET.get('ranking')
    date = request.GET.get('date')
    if ranking not in ['1', '2', '3']:
        return JsonResponse({
            'status': 404,
            'message': 'rankingが正しくない'
        })

    if date is None:
        return JsonResponse({
            'status': 404,
            'message': '日付が正しくない',
        })

    try:
        content = DairyContent.objects.get(user_object=request.user, ranking=ranking,
                                           date=datetime.datetime.strptime(date,
                                                                           '%Y-%m-%d').date()).content
        return JsonResponse({
            'status': 200,
            'content': content
        })
    except DairyContent.DoesNotExist:
        return JsonResponse({
            'status': 404,
        })


@login_required
@require_POST
def delete_dairy_content(request: HttpRequest) -> JsonResponse:
    try:
        instance = DairyContent.objects.get(user_object=request.user, content=request.POST.get('content'),
                                            ranking=request.POST.get('ranking'), date=request.POST.get('date'))
        instance.delete()
        return JsonResponse({
            'status': 200,
        })
    except DairyContent.DoesNotExist:
        return JsonResponse({
            'status': 404
        })


class CreateCategoryView(LoginRequiredMixin, CreateView):
    model = PictureCategory
    form_class = CategoryForm
    template_name = 'dairyApp/create_and_edit_category.html'

    def form_valid(self, form):
        instance_picture_category = form.save(commit=False)
        instance_picture_category.user_object = self.request.user
        instance_picture_category.picture_count = 0
        instance_picture_category.save()
        return HttpResponseRedirect(reverse_lazy('show_pictures'))


class EditCategoryView(LoginRequiredMixin, UpdateView):
    model = PictureCategory
    template_name = 'dairyApp/create_and_edit_category.html'
    form_class = CategoryForm

    def get_queryset(self):
        try:
            return PictureCategory.objects.filter(user_object=self.request.user, pk=self.kwargs['pk'])
        except PictureCategory.DoesNotExist:
            raise Http404('not access')

    def form_valid(self, form):
        if self.object.user_object != self.request.user:
            raise Http404('not access')
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy('show_pictures', kwargs={'category_id': self.kwargs['pk']})


class DeleteCategoryView(LoginRequiredMixin, DeleteView):
    model = PictureCategory
    template_name = 'dairyApp/delete_category.html'

    def get_queryset(self):
        try:
            return PictureCategory.objects.filter(pk=self.kwargs['pk'], user_object=self.request.user)
        except PictureCategory.DoesNotExist:
            raise Http404('not access')

    def form_valid(self, form):
        print(self.object.user_object, self.request.user)
        if self.object.user_object != self.request.user:
            raise Http404('not access')
        self.object.delete()
        return HttpResponseRedirect(reverse_lazy('show_pictures'))


class ShowPicturesView(LoginRequiredMixin, ListView):
    model = DairyPicture
    paginate_by = 50
    template_name = 'dairyApp/show_pictures.html'

    def get_queryset(self):
        try:
            category_id = self.kwargs['category_id']
            instance_category = PictureCategory.objects.get(
                user_object=self.request.user, pk=category_id)
            return DairyPicture.objects.filter(user_object=self.request.user,
                                               category=instance_category)
        except PictureCategory.DoesNotExist:
            raise Http404('not find')

        except KeyError:
            print('test')
            for pic in DairyPicture.objects.all():
                print(pic.image.url)
            return DairyPicture.objects.filter(user_object=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['picture_categories'] = PictureCategory.objects.filter(
            user_object=self.request.user)
        return context


@login_required
def create_dairy_picture(request: HttpRequest, date: str):
    if request.method == 'POST':
        form = DairyPictureForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            instance_dairy_picture = DairyPicture()
            instance_dairy_picture.title = request.POST['title']
            instance_dairy_picture.comment = request.POST['comment']
            instance_dairy_picture.image = request.FILES['image']
            instance_dairy_picture.user_object = request.user

            try:
                category_pk = request.POST['category']
                instance_dairy_picture.category = PictureCategory.objects.get(pk=category_pk,
                                                                              user_object=request.user)
                instance_picture_category = PictureCategory.objects.get(
                    pk=category_pk, user_object=request.user)
                instance_picture_category.picture_count += 1
                instance_picture_category.save()

            except ValueError:
                instance_dairy_picture.category = None

            instance_dairy_picture.date = create_date_obj(date)
            instance_dairy_picture.save()
            return redirect('index')
    else:
        print(request.user)
        form = DairyPictureForm(user_object=request.user)
    return render(request, 'dairyApp/create_and_edit_dairy_picture.html', {'form': form})


class DeleteDairyPictureView(LoginRequiredMixin, DeleteView):
    model = DairyPicture
    template_name = 'dairyApp/delete_dairy_picture.html'

    def get_queryset(self):
        try:
            return DairyPicture.objects.filter(user_object=self.request.user, pk=self.kwargs['pk'])
        except DairyPicture.DoesNotExist:
            raise Http404('not access')

    # TODO: redirect先を前にいたページにする
    def form_valid(self, form):
        if self.request.user != self.object.user_object:
            raise Http404('not access')
        category = self.object.category
        if category is not None:
            category.picture_count -= 1
            category.save()

        self.object.delete()
        return HttpResponseRedirect(reverse_lazy('index'))


class EditDairyPictureView(LoginRequiredMixin, UpdateView):
    model = DairyPicture
    template_name = 'dairyApp/create_and_edit_dairy_picture.html'
    form_class = DairyPictureForm

    def get_queryset(self):
        try:
            return DairyPicture.objects.filter(user_object=self.request.user, pk=self.kwargs['pk'])
        except DairyPicture.DoesNotExist:
            raise Http404('not access')

    def get_form_kwargs(self):
        kwargs = super(EditDairyPictureView, self).get_form_kwargs()
        kwargs.update({'user_object': self.request.user})
        return kwargs

    def form_valid(self, form):
        if self.request.user != self.object.user_object:
            raise Http404('not access')

        if DairyPicture.objects.get(pk=self.kwargs['pk']).category != self.object.category:
            instance_category = DairyPicture.objects.get(
                pk=self.kwargs['pk']).category
            if instance_category is not None:
                instance_category.picture_count -= 1
                instance_category.save()
            instance_category = self.object.category
            if instance_category is not None:
                instance_category.picture_count += 1
                instance_category.save()

        self.object.save()
        return HttpResponseRedirect(reverse_lazy('index'))


@login_required
@require_GET
def get_dairy_picture(request: HttpRequest) -> JsonResponse:
    try:

templates/dairyApp/create_and_edit_category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <form method="post" class="py-5 text-center">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
    {% if edit_category_pk %}
        <a href="{% url 'delete_category' edit_category_pk %}">削除</a>
    {% endif %}
{% endblock content %}

templates/dairyApp/create_and_edit_dairy_picture.html
{% extends 'base.html' %}

{% block content %}
    <form class="text-center" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input class="border-2 border-black" type="submit" value="Save">
    </form>
    {% if edit_picture_pk %}
    <a href="{% url 'delete_dairy_picture' edit_picture_pk %}">削除</a>
    {% endif %}
{% endblock content %}

templates/dairyApp/create_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
    </form>
</body>
</html>

templates/dairyApp/create_picture.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

templates/dairyApp/delete_category.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>本当に削除しますか "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="削除">
    </form>
{% endblock content %}

templates/dairyApp/delete_dairy_picture.html
{% extends 'base.html' %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>本当に削除しますか "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="削除">
    </form>
{% endblock content %}

templates/dairyApp/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="{% static "fullcalendar/main.css" %}" rel="stylesheet">
    <script src="{% static "js/onloadEvent.js" %}" type="text/javascript"></script>
    <script src="{% static "fullcalendar/main.js" %}" type="text/javascript"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var calendarEl = document.getElementById("calendar");
            var calendar = new FullCalendar.Calendar(calendarEl, {
                initialView: "dayGridMonth",
            });
            calendar.on('dateClick', function (info) {
                console.log('click on ' + info.dateStr);
                console.log('before clickOnCalendarEvent func');
                clickOnCalendarEvent(info.dateStr);
            })
            calendar.render();
        });
    </script>
    <script>
        const postDairyContentUrl = "{% url 'post_dairy_content' %}"
        const getDairyContentUrl = "{% url 'get_dairy_content' %}"
        const deleteDairyContentUrl = "{% url 'delete_dairy_content' %}"
        const postDairyPictureUrl = "{% url 'create_dairy_picture' date=today %}"
        const getDairyPictureUrl = "{% url 'get_dairy_picture' %}"
    </script>
{% endblock head %}

{% block content %}
    <div id="calendar"></div>
    <div id="main" class="py-5">
        <div id="dairy-content-form" class={{ today }}>
            <p id="show-date" class="flex justify-evenly mb-1"></p>
            <div id="show-picture">
                <ul id="show-picture-ul" class="flex justify-evenly"></ul>
            </div>
            <div id="save-picture-button" class="text-center">
                <button onclick="postDairyPicture()" class="border-solid border-2 border-black p-1">写真を投稿</button>
            </div>
            <div id="form-1" class="text-center py-5">
                <p id="alert-not-saved-1"></p>
                <label class="">
                    1位
                    <textarea id="textarea-1" class="border-2 border-black w-1/2 align-middle"
                              name="content-form"></textarea>
                </label>
                <button type="submit" onclick="postDairyContent(1)" class="border-solid border-2 border-black p-1">記録</button>
                <button type="submit" onclick="deleteDairyContent(1)" class="border-solid border-2 border-black p-1" >削除</button>
            </div>
            <div id="form-2" class="text-center py-5">
                <p id="alert-not-saved-2"></p>
                <label>
                    2位
                    <textarea id="textarea-2" class="border-2 border-black w-1/2 align-middle"
                              name=content-form"></textarea>
                </label>
                <button type="submit" onclick="postDairyContent(2)" class="border-solid border-2 border-black p-1">記録</button>
                <button type="submit" onclick="deleteDairyContent(2)" class="border-solid border-2 border-black p-1">削除</button>
            </div>
            <div id="form-3" class="text-center py-5">
                <p id="alert-not-saved-3"></p>
                <label>
                    3位
                    <textarea id="textarea-3" class="border-2 border-black w-1/2 align-middle"
                              name="content-form"></textarea>
                </label>
                <button type="submit" onclick="postDairyContent(3)" class="border-solid border-2 border-black p-1">記録</button>
                <button type="submit" onclick="deleteDairyContent(3)" class="border-solid border-2 border-black p-1">削除</button>
            </div>
        </div>
    </div>
    <script src="{% static "js/postDairyContent.js" %}" type="text/javascript"></script>
    <script src="{% static "js/splitDate.js" %}" type="text/javascript"></script>
    <script src="{% static "js/getDairyContent.js" %}" type="text/javascript"></script>
    <script src="{% static "js/deleteDairyContent.js" %}" type="text/javascript"></script>
    <script src="{% static "js/clickOnCalendarEvent.js" %}" type="text/javascript"></script>
    <script src="{% static "js/postDairyPicture.js" %}" type="text/javascript"></script>
    <script src="{% static "js/getDairyPicture.js" %}" type="text/javascript"></script>
    <script src="{% static "js/checkExchangeForm.js" %}" type="text/javascript"></script>
    
{% endblock content %}

templates/dairyApp/show_pictures.html
{% extends 'base.html' %}

{% block content %}
    <div id="content" class="flex">
        <div id="sidebar" class="w-2/6">
            <ul>
                {% for category in picture_categories %}
                    <li><a class="flex" href="{% url 'show_pictures' category.pk %}"><p
                            class="text-lg mx-3">{{ category.title }}</p>
                        <p class="mx-3">{{ category.picture_count }}</p></a></li>
                {% endfor %}
            </ul>
        </div>
        <div id="main" class="w-4/6">
            {% if category_id %}
                <a href="{% url 'edit_category' category_id %}">カテゴリーを編集</a>
            {% endif %}
            <ul class="flex flex-wrap list-none">
                {% for item in dairypicture_list %}
                    <li class="p-2.5">
                        <p>{{ item.title }}</p>
                        <img src="{{ item.image.url }}" width="200px" height="200px">
                        <a href="{% url 'edit_dairy_picture' item.pk %}">編集</a>
                        <a href="{% url 'delete_dairy_picture' item.pk %}">削除</a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock content %}